[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
language = "system"
entry = "bash -c 'cargo fmt; exit 0'"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
language = "system"
entry = "cargo clippy --all-targets --all-features -- -D warnings"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "rumdl"
name = "rumdl"
language = "system"
entry = "bash -c 'rumdl check --fix; exit 0'"
types = ["markdown"]
pass_filenames = false
